# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/c8650/extract-files.sh - DO NOT EDIT

# All the blobs necessary for c8650
PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/bin/akmd8962:system/bin/akmd8962 \
    vendor/huawei/c8650/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/huawei/c8650/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/huawei/c8650/proprietary/bin/rild:system/bin/rild \
    vendor/huawei/c8650/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/c8650/proprietary/bin/compassd:system/bin/compassd \
    vendor/huawei/c8650/proprietary/bin/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/c8650/proprietary/bin/modempre:system/bin/modempre \
    vendor/huawei/c8650/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/huawei/c8650/proprietary/etc/bluetooth/BCM4329.hcd:system/etc/bluetooth/BCM4329.hcd \
    vendor/huawei/c8650/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/c8650/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/c8650/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/c8650/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/c8650/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/c8650/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/c8650/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/c8650/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/huawei/c8650/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/c8650/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/c8650/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/c8650/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/c8650/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/c8650/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/c8650/proprietary/lib/libnv.so:obj/lib/libnv.so \
    vendor/huawei/c8650/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/c8650/proprietary/lib/libwmsts.so:obj/lib/libwmsts.so \
    vendor/huawei/c8650/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/c8650/proprietary/lib/libpbmlib.so:obj/lib/libpbmlib.so \
    vendor/huawei/c8650/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/c8650/proprietary/lib/libdss.so:obj/lib/libdss.so \
    vendor/huawei/c8650/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/huawei/c8650/proprietary/lib/libauth.so:obj/lib/libauth.so \
    vendor/huawei/c8650/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/c8650/proprietary/lib/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/huawei/c8650/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/c8650/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so \
    vendor/huawei/c8650/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/c8650/proprietary/lib/libmmipl.so:obj/lib/libmmipl.so \
    vendor/huawei/c8650/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/huawei/c8650/proprietary/lib/libmm-adspsvc.so:obj/lib/libmm-adspsvc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAacDec.so:obj/lib/libOmxAacDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxWmvDec.so:obj/lib/libOmxWmvDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAdpcmDec.so:obj/lib/libOmxAdpcmDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxH264Dec.so:obj/lib/libOmxH264Dec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrDec.so:obj/lib/libOmxAmrDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrwbDec.so:obj/lib/libOmxAmrwbDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxWmaDec.so:obj/lib/libOmxWmaDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxMp3Dec.so:obj/lib/libOmxMp3Dec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxMpeg4Dec.so:obj/lib/libOmxMpeg4Dec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrRtpDec.so:obj/lib/libOmxAmrRtpDec.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAacEnc.so:obj/lib/libOmxAacEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxEvrcEnc.so:obj/lib/libOmxEvrcEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxAmrEnc.so:obj/lib/libOmxAmrEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxQcelp13Enc.so:obj/lib/libOmxQcelp13Enc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/huawei/c8650/proprietary/lib/libOmxVidEnc.so:obj/lib/libOmxVidEnc.so \
    vendor/huawei/c8650/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_aacdec_sharedlibrary.so:obj/lib/libomx_aacdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_amrdec_sharedlibrary.so:obj/lib/libomx_amrdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_amrenc_sharedlibrary.so:obj/lib/libomx_amrenc_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_avcdec_sharedlibrary.so:obj/lib/libomx_avcdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_m4vdec_sharedlibrary.so:obj/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_mp3dec_sharedlibrary.so:obj/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/huawei/c8650/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so\
    vendor/huawei/c8650/proprietary/lib/libomx_sharedlibrary.so:obj/lib/libomx_sharedlibrary.so\
    vendor/huawei/c8650/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/huawei/c8650/proprietary/lib/libcommondefs.so:obj/lib/libcommondefs.so \
    vendor/huawei/c8650/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/huawei/c8650/proprietary/lib/libloc_api-rpc-qc.so:obj/lib/libloc_api-rpc-qc.so \
    vendor/huawei/c8650/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/c8650/proprietary/lib/libhwrpc.so:obj/lib/libhwrpc.so \
    vendor/huawei/c8650/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/huawei/c8650/proprietary/lib/liboem_rapi.so:obj/lib/liboem_rapi.so \
    vendor/huawei/c8650/proprietary/lib/libmmprocess.so:system/lib/libmmprocess.so \
    vendor/huawei/c8650/proprietary/lib/libmmprocess.so:obj/lib/libmmprocess.so \
    vendor/huawei/c8650/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/huawei/c8650/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/huawei/c8650/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/huawei/c8650/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/huawei/c8650/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/c8650/proprietary/lib/hw/sensors.default.so:obj/lib/hw/sensors.default.so \
    vendor/huawei/c8650/proprietary/lib/hw/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \
    vendor/huawei/c8650/proprietary/lib/hw/copybit.msm7k.so:obj/lib/hw/copybit.msm7k.so \
    vendor/huawei/c8650/proprietary/lib/hw/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so \
    vendor/huawei/c8650/proprietary/lib/hw/gralloc.msm7k.so:obj/lib/hw/gralloc.msm7k.so \
    vendor/huawei/c8650/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/huawei/c8650/proprietary/lib/hw/lights.default.so:obj/lib/hw/lights.default.so \
#    vendor/huawei/c8650/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
#    vendor/huawei/c8650/proprietary/lib/egl/libEGL_adreno200.so:obj/lib/egl/libEGL_adreno200.so \
#    vendor/huawei/c8650/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
#    vendor/huawei/c8650/proprietary/lib/egl/libGLESv1_CM_adreno200.so:obj/lib/egl/libGLESv1_CM_adreno200.so \
#    vendor/huawei/c8650/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
#    vendor/huawei/c8650/proprietary/lib/egl/libGLESv2_adreno200.so:obj/lib/egl/libGLESv2_adreno200.so \
#    vendor/huawei/c8650/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
#    vendor/huawei/c8650/proprietary/lib/egl/libq3dtools_adreno200.so:obj/lib/egl/libq3dtools_adreno200.so \
#    vendor/huawei/c8650/proprietary/lib/libgsl.so:system/lib/libgsl.so


PRODUCT_COPY_FILES += \
    vendor/huawei/c8650/proprietary/lib/new/libC2D2.so:system/lib/libC2D2.so \
    vendor/huawei/c8650/proprietary/lib/new/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/huawei/c8650/proprietary/lib/new/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/huawei/c8650/proprietary/lib/new/libgsl.so:system/lib/libgsl.so \
    vendor/huawei/c8650/proprietary/lib/new/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/huawei/c8650/proprietary/lib/new/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/c8650/proprietary/lib/new/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/c8650/proprietary/lib/new/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/c8650/proprietary/lib/new/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so
